# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 26dc1a59d45369c2e91a1ee7c1fdc94f41f84cd2775b11b60e14e6ae5d88e63d9fef7f03e5e384c79f0183d0f7728cb339cc3d19000ea3578b41cba2cad537aa

test:
  secret_key_base: 37e1e23c5f15b7a6369345e24d423b1fe32dbfa7917212e9c9848e56f979cc299983b0105f44858ada72274c5c55e03d39d96016bb78d5555f78354e5a7102a2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
